default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  port: 5432
  username: meyagen
  password: 1412017

development:
  <<: *default
  database: todo_development

test:
  <<: *default
  database: todo_test

production:
  <<: *default
  database: todo_production
  username: todo
  password: <%= ENV['TODO_DATABASE_PASSWORD'] %>
