default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  port: 5432
  username: kickstarter
  password: k!ckst@rt3r

development:
  <<: *default
  database: idea_kickstarter_development

test:
  <<: *default
  database: idea_kickstarter_test

production:
  <<: *default
  database: idea_kickstarter_production
  username: idea_kickstarter
  password: <%= ENV['IDEA_KICKSTARTER_DATABASE_PASSWORD'] %>
